### PR TITLE
Adds macOS 11.1 toolchain.

### PR DESCRIPTION
**Pull request by olliwang**

### CODE REVIEW

**Review by ruslo — CHANGES_REQUESTED** [review]
Entries in `toolchain_table.py` are missing:
- https://github.com/ruslo/polly/blob/master/bin/detail/toolchain_table.py

**Comment by olliwang** [comment]
> Entries in `toolchain_table.py` are missing:
> 
> * https://github.com/ruslo/polly/blob/master/bin/detail/toolchain_table.py

Just updated. Thanks.

**Review by ruslo — CHANGES_REQUESTED** [review]
> Conflicting files
> bin/detail/toolchain_table.py
> osx-11-1-dep-10-10-cxx17.cmake

Please resolve conflicts

**Comment by olliwang** [comment]
My bad. Just fixed it.

**Review by ruslo — DISMISSED** [review]
Looks good, thank you 👍

**Review by ruslo — APPROVED** [review]

**Pull request merged**
