### PR TITLE
correct bitcode support for iOS updated (toolchain ID 3)

### PR DESCRIPTION
**Pull request by ikliashchou**
Initial PR [here](https://github.com/ruslo/polly/pull/157). Sorry, I've killed that branch by occasion.

### CODE REVIEW

**Comment by ruslo** [comment]
I've tried `Debug` build and looks like `-fembed-bitcode` flag used. You've mentioned before that it's not appropriate because of build time and that `-fembed-bitcode-marker` should be used instead:
* https://github.com/ruslo/hunter/issues/873#issuecomment-314450752

**Comment by ruslo** [comment]
Try to add
```
set(CMAKE_XCODE_ATTRIBUTE_BITCODE_GENERATION_MODE[variant=Debug] "marker")                                                                       
set(CMAKE_XCODE_ATTRIBUTE_BITCODE_GENERATION_MODE "bitcode")
```
should do the trick. Please add comments with description of all the bitcode feature peculiarities. Also I guess it make sense to add this link:
* https://medium.com/@heitorburger/static-libraries-frameworks-and-bitcode-6d8f784478a9

**Comment by ikliashchou** [comment]
Seems that the tests hanged again, can you restart them please?

**Comment by ruslo** [comment]
> Seems that the tests hanged again, can you restart them please?

It's a Travis glitch. There is no bitcode tests currently anyway, I've run tests locally.

**Pull request merged**
