### PR TITLE
Android NDK libc++ support

### PR DESCRIPTION
**Pull request by fwinnen**
- Added support for c++_static and c++_shared
- Added some toolchin to use those features

Sadly  os/android.toolchain.cmake had inconsistent indents, which my IDE fixed

### CODE REVIEW

**Comment by ruslo** [comment]
> Sadly os/android.toolchain.cmake had inconsistent indents, which my IDE fixed

This file should be used as is because it's copy-pasted from https://github.com/taka-no-me/android-cmake

**Comment by fwinnen** [comment]
Yes, i think the initial libc++ support was a fork of that. I just added some exported variables to it and fixed bugs i encountered. I don't have references to that fork anymore since that file got in our repo and evolved there.

I could try to get those fixes and libc++ support upstream to take-no-me.

Just thought, that someone eventually wants to use libc++ with polly, so i pushed it here, but i am totally fine to just use my fork

**Comment by ruslo** [comment]
>  I don't have references to that fork anymore since that file got in our repo and evolved there

Okay, so you have some improvements there. I was thinking that it's just formatting fixes.

> I could try to get those fixes and libc++ support upstream to take-no-me.

From my experience it will have no effect: https://github.com/taka-no-me/android-cmake/pull/50

> Just thought, that someone eventually wants to use libc++ with polly, so i pushed it here, but i am totally fine to just use my fork

Please push your updates here first: https://github.com/hunter-packages/android-cmake though I'm still thinking that changes should be as minimal as possible.

**Comment by pretyman** [comment]
> From my experience it will have no effect: taka-no-me/android-cmake#50

Maybe we could make polly's version new upstream and create an issue/pull request pointing to this repository on the title? taka-no-me/android-cmake seems to be abandoned.

**Comment by ruslo** [comment]
> Maybe we could make polly's version new upstream and create an issue/pull request pointing to this repository on the title?

Luckily this toolchain will be not needed soon. CMake 3.7+ will have Android support from the box: https://gitlab.kitware.com/cmake/cmake/merge_requests/62. I've already prepared updates in branch [new.android](https://github.com/ruslo/polly/commits/new.android).

**Comment by pretyman** [comment]
> I've already prepared updates in branch new.android.

What CMake branch are you using to pass the test on: https://github.com/ruslo/polly/blob/new.android/os/android.cmake#L30 ? `master`, at this time, is still 3.6

**Comment by ruslo** [comment]
> What CMake branch are you using to pass the test on

I'm waiting for official release, branch `new.android` has a "red" status for now: https://travis-ci.org/ruslo/polly/builds/155793608

**Comment by bhack** [comment]
I think that the new Cmake release is available now.

**Comment by ruslo** [comment]
I know. I'm in process of testing the whole Polly/Hunter system with the few key packages for Android. It will take some time. Also there will be some new variables introduced in future version:
* https://gitlab.kitware.com/cmake/cmake/merge_requests/254

WIP progress available in branches `new.android`:
* https://github.com/ruslo/polly/tree/new.android
* https://github.com/ruslo/hunter/tree/new.android

**Comment by ruslo** [comment]
> Luckily this toolchain will be not needed soon. CMake 3.7+ will have Android support from the box: https://gitlab.kitware.com/cmake/cmake/merge_requests/62. I've already prepared updates in branch new.android.

In `master` now. @fwinnen I'm closing this one, please open new pull request based on new Android toolchains.

**Pull request closed without merging**
